"""Run the segmentation pipeline over the synthetic demo sequence and build figures.

Produces, under `figures/`:

  pipeline-stages.png   the six-panel worked example (input -> five pipeline stages)
  demo-sequence.gif     original vs segmented, animated over the ten frames
  demo-recovery.png     oil area ratio and recovery rate for the demo sequence

The algorithm itself is imported from `vis.py` and `cla.py` unchanged, so these
figures are generated by exactly the code that produced the published analysis.

Usage:
    python demo/make_demo_data.py
    python demo/run_demo.py
"""

import os
import sys

import cv2
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from vis import process_image  # noqa: E402  (path set up above)

FRAME_DIR = "img/DEMO"
FIG_DIR = "figures"
STEP_DIR = "visualisation"

STAGE_FILES = [
    ("01_initial_mask.jpg", "1. Colour-distance mask", "Euclidean distance to #878874 < 25"),
    ("02_cleaned_mask.jpg", "2. Morphological opening", "3x3 kernel, 2 iterations"),
    ("03_large_component_mask.jpg", "3. Connected components", "components >= 250 px retained"),
    ("04_edge_mask.jpg", "4. Gaussian-blurred edges", "5x5 kernel"),
    ("05_final_image.jpg", "5. Weighted overlay", "0.7 original + 0.3 masked"),
]


def _load_rgb(path):
    image = cv2.imread(path)
    if image is None:
        raise FileNotFoundError(path)
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)


def build_stage_figure():
    """Six-panel figure: the input frame followed by each intermediate stage."""
    first = os.path.join(FRAME_DIR, "T=1h.jpg")
    os.makedirs(STEP_DIR, exist_ok=True)
    ratio, _, _ = process_image(first, save_steps=True)
    print(f"stage figure: oil area ratio at T=1h is {ratio:.4f}")

    panels = [(_load_rgb(first), "Input frame (T = 1 h)", "synthetic micromodel, 960 x 720")]
    for filename, title, subtitle in STAGE_FILES:
        panels.append((_load_rgb(os.path.join(STEP_DIR, filename)), title, subtitle))

    fig, axes = plt.subplots(2, 3, figsize=(15, 9.4))
    for ax, (image, title, subtitle) in zip(axes.ravel(), panels):
        ax.imshow(image)
        ax.set_title(f"{title}\n", fontsize=12, fontweight="bold", pad=6)
        ax.set_xlabel(subtitle, fontsize=9, color="#555555", labelpad=8)
        ax.set_xticks([])
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_edgecolor("#cccccc")
    fig.suptitle(
        "Oil segmentation pipeline, stage by stage",
        fontsize=15, fontweight="bold", y=0.99,
    )
    fig.subplots_adjust(hspace=0.28, wspace=0.08)
    fig.tight_layout(rect=(0, 0, 1, 0.96), h_pad=2.4)
    out = os.path.join(FIG_DIR, "pipeline-stages.png")
    fig.savefig(out, dpi=96, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print("wrote", out)


def run_sequence():
    """Segment every demo frame; return the per-frame oil area ratios."""
    ratios, panels = [], []
    hour = 1
    while True:
        path = os.path.join(FRAME_DIR, f"T={hour}h.jpg")
        if not os.path.exists(path):
            break
        ratio, segmented, _ = process_image(path)
        original = cv2.imread(path)

        labelled = []
        for image, text in ((original, f"Original  T = {hour} h"),
                            (segmented, f"Segmented  oil ratio = {ratio:.3f}")):
            image = image.copy()
            cv2.rectangle(image, (0, 0), (image.shape[1], 46), (0, 0, 0), cv2.FILLED)
            cv2.putText(image, text, (12, 32), cv2.FONT_HERSHEY_SIMPLEX,
                        0.8, (255, 255, 255), 2, cv2.LINE_AA)
            labelled.append(image)

        pair = np.hstack(labelled)
        # Halve the resolution so the animation stays small enough to embed.
        pair = cv2.resize(pair, (pair.shape[1] // 2, pair.shape[0] // 2),
                          interpolation=cv2.INTER_AREA)
        panels.append(cv2.cvtColor(pair, cv2.COLOR_BGR2RGB))
        ratios.append(ratio)
        hour += 1

    out = os.path.join(FIG_DIR, "demo-sequence.gif")
    quantised = [Image.fromarray(p).quantize(colors=64, method=Image.MEDIANCUT)
                 for p in panels]
    quantised[0].save(out, save_all=True, append_images=quantised[1:],
                      duration=900, loop=0, optimize=True)
    print(f"wrote {out} ({len(panels)} frames, "
          f"{os.path.getsize(out) / 1e6:.1f} MB)")
    return ratios


def plot_demo(ratios):
    hours = np.arange(1, len(ratios) + 1)
    recovery = [(ratios[0] - r) / ratios[0] * 100 for r in ratios]

    fig, (left, right) = plt.subplots(1, 2, figsize=(12, 4.6))
    left.plot(hours, ratios, "o-", color="#8a7f4f", lw=2, ms=6)
    left.set_title("Oil area ratio", fontweight="bold")
    left.set_xlabel("Time (hours)")
    left.set_ylabel("Oil area / total area")

    right.plot(hours, recovery, "s-", color="#b23a48", lw=2, ms=6)
    right.set_title("Recovery rate", fontweight="bold")
    right.set_xlabel("Time (hours)")
    right.set_ylabel("Recovery (%)")

    for ax in (left, right):
        ax.grid(True, alpha=0.3)
        ax.set_xticks(hours)
        ax.spines[["top", "right"]].set_visible(False)

    fig.suptitle("Synthetic demo sequence, pipeline output", fontweight="bold")
    fig.tight_layout()
    out = os.path.join(FIG_DIR, "demo-recovery.png")
    fig.savefig(out, dpi=140, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print("wrote", out)


if __name__ == "__main__":
    os.makedirs(FIG_DIR, exist_ok=True)
    build_stage_figure()
    plot_demo(run_sequence())
